trainingInput:
  scaleTier: CUSTOM
  runtimeVersion: '1.14'
  pythonVersion: '3.5'
  masterType: n1-highcpu-16
  workerType: cloud_tpu
  workerCount: 1
  workerConfig:
    acceleratorConfig:
      type: TPU_V3
      count: 8